import type { WorkflowTemplate } from "../types";
export const AI_AUTOMATION_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "daily-ai-digest-notion-archive",
        name: "Daily AI Digest Notion Archive",
        description: "Collect daily metrics, summarize with OpenAI, archive a report in Notion, and notify Slack + Discord.",
        category: "ai-automation",
        difficulty: "intermediate",
        estimatedSetupMinutes: 10,
        tags: ["cron", "http", "openai", "notion", "slack", "discord", "log"],
        availableTriggerId: "manual",
        highlights: ["Daily digest", "AI summary", "Notion archive", "Multi-channel notify"],
        requiredCredentials: ["openai", "notion", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["digest-gemini"], description: "OpenAI credential for summarization" },
            { platform: "notion", nodeIds: ["digest-notion"], description: "Notion credential for report archive" },
            { platform: "slack", nodeIds: ["digest-slack"], description: "Slack credential for posting" },
            { platform: "discord", nodeIds: ["digest-discord"], description: "Discord credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "digest-http",
                field: "url",
                label: "Metrics API URL",
                placeholder: "https://api.example.com/daily-metrics",
                type: "text",
                required: true,
            },
            {
                nodeId: "digest-gemini",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "digest-notion",
                field: "databaseId",
                label: "Notion Reports Database ID",
                placeholder: "Paste Notion database/data source link or ID",
                type: "text",
                required: true,
            },
            {
                nodeId: "digest-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "digest-cron",
                type: "cronTrigger",
                position: { x: 80, y: 240 },
                data: {
                    label: "Daily Schedule",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "daily",
                    hour: 8,
                    minute: 0,
                    timezone: "UTC",
                },
            },
            {
                id: "digest-http",
                type: "httpTrigger",
                position: { x: 320, y: 240 },
                data: {
                    label: "Fetch Metrics",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "digestMetrics",
                    method: "GET",
                    url: "https://httpbin.org/json",
                    headers: [],
                },
            },
            {
                id: "digest-transform",
                type: "transformNode",
                position: { x: 560, y: 240 },
                data: {
                    label: "Prepare Context",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "digestContext",
                    expression: '{"summary":"Create a concise KPI digest from these metrics.","summaryPrompt":"Create a concise KPI digest from these metrics.","metrics":{json digestMetrics},"runAt":"{digest-cron.triggeredAt}"}',
                },
            },
            {
                id: "digest-gemini",
                type: "openaiNode",
                position: { x: 800, y: 240 },
                data: {
                    label: "Summarize with OpenAI",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "digestSummary",
                    credentialId: "",
                    model: "",
                    prompt: "{digestContext.data.summaryPrompt}\n{json digestContext.data.metrics}",
                    temperature: 0.2,
                },
            },
            {
                id: "digest-notion",
                type: "notionNode",
                position: { x: 1040, y: 100 },
                data: {
                    label: "Archive in Notion",
                    nodeType: "notionNode",
                    isConfigured: false,
                    responseName: "digestArchive",
                    credentialId: "",
                    operation: "create",
                    databaseId: "",
                    propertiesTemplate: '{"Name":{"title":[{"text":{"content":"Daily AI Digest {digest-cron.triggeredAt}"}}]}}',
                    childrenTemplate: '[{"object":"block","type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":{json digestSummary.data}}}]}}]',
                },
            },
            {
                id: "digest-slack",
                type: "slackNode",
                position: { x: 1040, y: 200 },
                data: {
                    label: "Post Digest",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "digestSlack",
                    credentialId: "",
                    channel: "",
                    message: "Daily digest ready:\n{digestSummary.data}",
                },
            },
            {
                id: "digest-discord",
                type: "discordNode",
                position: { x: 1040, y: 300 },
                data: {
                    label: "Post to Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "digestDiscord",
                    credentialId: "",
                    message: "Daily digest ready:\n{digestSummary.data}",
                },
            },
            {
                id: "digest-log",
                type: "logNode",
                position: { x: 1040, y: 400 },
                data: {
                    label: "Digest Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Daily digest distributed at {digest-cron.triggeredAt}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "digest-cron", target: "digest-http" },
            { id: "e2", source: "digest-http", target: "digest-transform" },
            { id: "e3", source: "digest-transform", target: "digest-gemini" },
            { id: "e4", source: "digest-gemini", target: "digest-notion" },
            { id: "e5", source: "digest-gemini", target: "digest-slack" },
            { id: "e6", source: "digest-gemini", target: "digest-discord" },
            { id: "e7", source: "digest-gemini", target: "digest-log" },
        ],
    },
    {
        id: "meeting-notes-notion-sync-lite",
        name: "Meeting Notes Notion Sync Lite",
        description: "Turn rough meeting notes into action items, archive them in Notion, and notify the team.",
        category: "ai-automation",
        difficulty: "beginner",
        estimatedSetupMinutes: 6,
        tags: ["manual", "anthropic", "transform", "notion", "slack", "log"],
        availableTriggerId: "manual",
        highlights: ["Meeting note cleanup", "Notion archive", "Team handoff"],
        requiredCredentials: ["anthropic", "notion", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["meet-anthropic"], description: "Anthropic credential for note cleanup" },
            { platform: "notion", nodeIds: ["meet-notion"], description: "Notion credential for action-item archive" },
            { platform: "slack", nodeIds: ["meet-slack"], description: "Slack credential for team update" },
        ],
        fieldRequirements: [
            {
                nodeId: "meet-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "meet-notion",
                field: "databaseId",
                label: "Notion Meeting Database ID",
                placeholder: "Paste Notion database/data source link or ID",
                type: "text",
                required: true,
            },
            {
                nodeId: "meet-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "meet-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "meet-anthropic",
                type: "anthropicNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Extract Action Items",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "meetingActions",
                    credentialId: "",
                    model: "",
                    prompt: "Convert these meeting notes into action items with owners and deadlines.",
                    temperature: 0.2,
                },
            },
            {
                id: "meet-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Prepare Notion Payload",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "meetingPayload",
                    expression: '{"summary":{json meetingActions.data}}',
                },
            },
            {
                id: "meet-notion",
                type: "notionNode",
                position: { x: 800, y: 140 },
                data: {
                    label: "Archive in Notion",
                    nodeType: "notionNode",
                    isConfigured: false,
                    responseName: "meetingArchive",
                    credentialId: "",
                    operation: "create",
                    databaseId: "",
                    propertiesTemplate: '{"Name":{"title":[{"text":{"content":"Meeting Actions {meet-manual.triggeredAt}"}}]}}',
                    childrenTemplate: '[{"object":"block","type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":{json meetingPayload.data.summary}}}]}}]',
                },
            },
            {
                id: "meet-slack",
                type: "slackNode",
                position: { x: 1040, y: 200 },
                data: {
                    label: "Notify Team",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "meetingSlack",
                    credentialId: "",
                    channel: "",
                    message: "Meeting actions:\n{meetingPayload.data.summary}",
                },
            },
            {
                id: "meet-log",
                type: "logNode",
                position: { x: 1040, y: 320 },
                data: {
                    label: "Meeting Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Meeting notes processed at {meet-manual.triggeredAt}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "meet-manual", target: "meet-anthropic" },
            { id: "e2", source: "meet-anthropic", target: "meet-transform" },
            { id: "e3", source: "meet-transform", target: "meet-notion" },
            { id: "e4", source: "meet-notion", target: "meet-slack" },
            { id: "e5", source: "meet-notion", target: "meet-log" },
        ],
    },
    {
        id: "openai-quick-research-share-lite",
        name: "OpenAI Quick Research Share Lite",
        description: "Generate a quick research brief with OpenAI and distribute to Slack + Discord.",
        category: "ai-automation",
        difficulty: "beginner",
        estimatedSetupMinutes: 4,
        tags: ["manual", "openai", "transform", "slack", "discord"],
        availableTriggerId: "manual",
        highlights: ["Quick research draft", "Slack + Discord sharing"],
        requiredCredentials: ["openai", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["qr-openai"], description: "OpenAI credential for research drafting" },
            { platform: "slack", nodeIds: ["qr-slack"], description: "Slack credential for posting" },
            { platform: "discord", nodeIds: ["qr-discord"], description: "Discord credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "qr-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "qr-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "qr-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "qr-openai",
                type: "openaiNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Draft Research Brief",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "quickResearch",
                    credentialId: "",
                    model: "",
                    prompt: "Create a concise market update on workflow automation trends.",
                    temperature: 0.3,
                },
            },
            {
                id: "qr-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Format Brief",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "quickBrief",
                    expression: '{"message":{json quickResearch.data}}',
                },
            },
            {
                id: "qr-slack",
                type: "slackNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Share in Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "quickSlack",
                    credentialId: "",
                    channel: "",
                    message: "Research Brief:\n{quickBrief.data.message}",
                },
            },
            {
                id: "qr-discord",
                type: "discordNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Share in Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "quickDiscord",
                    credentialId: "",
                    message: "Research Brief:\n{quickBrief.data.message}",
                },
            },
            {
                id: "qr-log",
                type: "logNode",
                position: { x: 800, y: 360 },
                data: {
                    label: "Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Quick research workflow completed",
                },
            },
        ],
        edges: [
            { id: "e1", source: "qr-manual", target: "qr-openai" },
            { id: "e2", source: "qr-openai", target: "qr-transform" },
            { id: "e3", source: "qr-transform", target: "qr-slack" },
            { id: "e4", source: "qr-transform", target: "qr-discord" },
            { id: "e5", source: "qr-slack", target: "qr-log" },
        ],
    },
    {
        id: "openai-content-brief-notion-handoff",
        name: "OpenAI Content Brief Notion Handoff",
        description: "Generate a content brief with OpenAI, archive it in Notion, and hand it off to Slack.",
        category: "ai-automation",
        difficulty: "intermediate",
        estimatedSetupMinutes: 8,
        tags: ["manual", "openai", "transform", "notion", "slack", "log"],
        availableTriggerId: "manual",
        highlights: ["Content brief generation", "Notion archive", "Team handoff"],
        requiredCredentials: ["openai", "notion", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["brief-openai"], description: "OpenAI credential for brief generation" },
            { platform: "notion", nodeIds: ["brief-notion"], description: "Notion credential for brief archive" },
            { platform: "slack", nodeIds: ["brief-slack"], description: "Slack credential for team handoff" },
        ],
        fieldRequirements: [
            {
                nodeId: "brief-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "brief-notion",
                field: "databaseId",
                label: "Notion Briefs Database ID",
                placeholder: "Paste Notion database/data source link or ID",
                type: "text",
                required: true,
            },
            {
                nodeId: "brief-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "brief-manual",
                type: "manualTrigger",
                position: { x: 80, y: 240 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "brief-openai",
                type: "openaiNode",
                position: { x: 320, y: 240 },
                data: {
                    label: "Generate Brief",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "contentBrief",
                    credentialId: "",
                    model: "",
                    prompt: "Write a concise launch content brief in plain text under 900 characters. Include audience, angle, CTA, and one risk note.",
                    temperature: 0.4,
                },
            },
            {
                id: "brief-transform",
                type: "transformNode",
                position: { x: 560, y: 240 },
                data: {
                    label: "Prepare Handoff",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "briefPayload",
                    expression: '{"title":"Content Brief","summary":{json contentBrief.data}}',
                },
            },
            {
                id: "brief-notion",
                type: "notionNode",
                position: { x: 800, y: 180 },
                data: {
                    label: "Archive in Notion",
                    nodeType: "notionNode",
                    isConfigured: false,
                    responseName: "briefArchive",
                    credentialId: "",
                    operation: "create",
                    databaseId: "",
                    propertiesTemplate: '{"Name":{"title":[{"text":{"content":"Content Brief {brief-manual.triggeredAt}"}}]}}',
                    childrenTemplate: '[{"object":"block","type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":{json briefPayload.data.summary}}}]}}]',
                },
            },
            {
                id: "brief-slack",
                type: "slackNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Notify Team",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "briefSlack",
                    credentialId: "",
                    channel: "",
                    message: "New content brief ready:\n{briefPayload.data.summary}",
                },
            },
            {
                id: "brief-log",
                type: "logNode",
                position: { x: 1040, y: 340 },
                data: {
                    label: "Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Content brief handoff completed",
                },
            },
        ],
        edges: [
            { id: "e1", source: "brief-manual", target: "brief-openai" },
            { id: "e2", source: "brief-openai", target: "brief-transform" },
            { id: "e3", source: "brief-transform", target: "brief-notion" },
            { id: "e4", source: "brief-notion", target: "brief-slack" },
            { id: "e5", source: "brief-notion", target: "brief-log" },
        ],
    },
    {
        id: "multi-source-ai-research-agent",
        name: "Multi Source AI Research Agent",
        description: "Pull from two HTTP sources, synthesize with OpenAI + Anthropic, then publish to Slack with a run log.",
        category: "ai-automation",
        difficulty: "advanced",
        estimatedSetupMinutes: 14,
        tags: ["manual", "http", "openai", "anthropic", "transform", "slack", "log"],
        availableTriggerId: "manual",
        highlights: ["Multi-source ingestion", "Dual-model synthesis", "Structured publication"],
        requiredCredentials: ["openai", "anthropic", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["ms-openai"], description: "OpenAI credential for first-pass synthesis" },
            { platform: "anthropic", nodeIds: ["ms-gemini"], description: "Anthropic credential for refinement" },
            { platform: "slack", nodeIds: ["ms-slack"], description: "Slack credential for final share" },
        ],
        fieldRequirements: [
            {
                nodeId: "ms-http-a",
                field: "url",
                label: "Source A URL",
                placeholder: "https://api.example.com/source-a",
                type: "text",
                required: true,
            },
            {
                nodeId: "ms-http-b",
                field: "url",
                label: "Source B URL",
                placeholder: "https://api.example.com/source-b",
                type: "text",
                required: true,
            },
            {
                nodeId: "ms-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "ms-gemini",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "ms-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "ms-manual",
                type: "manualTrigger",
                position: { x: 80, y: 300 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "ms-http-a",
                type: "httpTrigger",
                position: { x: 320, y: 220 },
                data: {
                    label: "Fetch Source A",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "sourceA",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "ms-http-b",
                type: "httpTrigger",
                position: { x: 320, y: 380 },
                data: {
                    label: "Fetch Source B",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "sourceB",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "ms-openai",
                type: "openaiNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Synthesize Draft",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "researchDraft",
                    credentialId: "",
                    model: "",
                    prompt: "Synthesize these sources into a unified draft: A={json sourceA}, B={json sourceB}",
                    temperature: 0.2,
                },
            },
            {
                id: "ms-gemini",
                type: "anthropicNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Refine Research",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "researchRefined",
                    credentialId: "",
                    model: "",
                    prompt: "Improve this research brief and add key takeaways: {researchDraft.data}",
                    temperature: 0.2,
                },
            },
            {
                id: "ms-transform",
                type: "transformNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Prepare Publish Payload",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "researchPayload",
                    expression: '{"title":"Research Brief","summary":{json researchRefined.data}}',
                },
            },
            {
                id: "ms-slack",
                type: "slackNode",
                position: { x: 1280, y: 220 },
                data: {
                    label: "Share in Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "researchSlack",
                    credentialId: "",
                    channel: "",
                    message: "Research brief generated:\n{researchPayload.data.summary}",
                },
            },
            {
                id: "ms-log",
                type: "logNode",
                position: { x: 1520, y: 220 },
                data: {
                    label: "Research Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Research brief completed at {ms-manual.triggeredAt}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "ms-manual", target: "ms-http-a" },
            { id: "e2", source: "ms-manual", target: "ms-http-b" },
            { id: "e3", source: "ms-http-a", target: "ms-openai" },
            { id: "e4", source: "ms-http-b", target: "ms-openai" },
            { id: "e5", source: "ms-openai", target: "ms-gemini" },
            { id: "e6", source: "ms-gemini", target: "ms-transform" },
            { id: "e7", source: "ms-transform", target: "ms-slack" },
            { id: "e8", source: "ms-slack", target: "ms-log" },
        ],
    },
    {
        id: "dual-model-governance-review",
        name: "Dual Model Governance Review",
        description: "Run multi-model governance checks and route pass/revise outcomes.",
        category: "ai-automation",
        difficulty: "advanced",
        estimatedSetupMinutes: 15,
        tags: ["manual", "openai", "anthropic", "condition", "slack", "log"],
        availableTriggerId: "manual",
        highlights: ["Multi-model review", "Governance routing", "Pass/revise handoff"],
        requiredCredentials: ["openai", "anthropic", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["gov-openai"], description: "OpenAI credential for first review" },
            { platform: "openai", nodeIds: ["gov-gemini"], description: "OpenAI credential for second review" },
            { platform: "anthropic", nodeIds: ["gov-anthropic"], description: "Anthropic credential for governance scoring" },
            { platform: "slack", nodeIds: ["gov-slack"], description: "Slack credential for pass notifications" },
        ],
        fieldRequirements: [
            {
                nodeId: "gov-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "gov-gemini",
                field: "model",
                label: "OpenAI Model (Second Pass)",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "gov-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "gov-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "gov-manual",
                type: "manualTrigger",
                position: { x: 80, y: 300 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "gov-openai",
                type: "openaiNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "OpenAI Review",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "openaiReview",
                    credentialId: "",
                    model: "",
                    prompt: "Review this draft for clarity and policy fit.",
                    temperature: 0.1,
                },
            },
            {
                id: "gov-gemini",
                type: "openaiNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "OpenAI Second Review",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "geminiReview",
                    credentialId: "",
                    model: "",
                    prompt: "Second-pass review over: {openaiReview.data}",
                    temperature: 0.1,
                },
            },
            {
                id: "gov-anthropic",
                type: "anthropicNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Governance Verdict",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "govVerdict",
                    credentialId: "",
                    model: "",
                    prompt: "You are a strict governance reviewer. Evaluate the review below and reply with exactly one lowercase word: pass or revise. Do not add extra text.\n\nReview:\n{geminiReview.data}",
                    temperature: 0,
                },
            },
            {
                id: "gov-transform",
                type: "transformNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Normalize Verdict",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "govResult",
                    expression: '{"decision":"{govVerdict.data}","summary":{json geminiReview.data}}',
                },
            },
            {
                id: "gov-condition",
                type: "conditionNode",
                position: { x: 1280, y: 220 },
                data: {
                    label: "Route Outcome",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{govResult.data.decision}",
                    routes: ["pass", "revise"],
                    defaultRoute: "revise",
                    rulesJson: '[{"route":"pass","operator":"contains","value":"pass"}]',
                    responseName: "govRoute",
                },
            },
            {
                id: "gov-slack",
                type: "slackNode",
                position: { x: 1520, y: 160 },
                data: {
                    label: "Outcome Notification",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "govSlack",
                    credentialId: "",
                    channel: "",
                    message: "Governance outcome: {govRoute.route}\n\nReview summary:\n{govResult.data.summary}",
                },
            },
            {
                id: "gov-log",
                type: "logNode",
                position: { x: 1520, y: 380 },
                data: {
                    label: "Decision Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Governance decision route: {govRoute.route}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "gov-manual", target: "gov-openai" },
            { id: "e2", source: "gov-openai", target: "gov-gemini" },
            { id: "e3", source: "gov-gemini", target: "gov-anthropic" },
            { id: "e4", source: "gov-anthropic", target: "gov-transform" },
            { id: "e5", source: "gov-transform", target: "gov-condition" },
            { id: "e6", source: "gov-condition", sourceHandle: "pass", target: "gov-slack" },
            { id: "e7", source: "gov-condition", sourceHandle: "revise", target: "gov-slack" },
            { id: "e7a", source: "gov-condition", sourceHandle: "pass", target: "gov-log" },
            { id: "e8", source: "gov-condition", sourceHandle: "revise", target: "gov-log" },
        ],
    },
];
