import type { WorkflowTemplate } from "../types";
export const DATA_ETL_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "webhook-discord-alert-router",
        name: "Webhook Discord Alert Router",
        description: "Route incoming webhook alerts to Slack or Discord based on severity.",
        category: "webhooks-apis",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["webhook", "transform", "condition", "slack", "discord"],
        availableTriggerId: "webhook",
        highlights: ["Simple routing", "Multi-channel alerts"],
        requiredCredentials: ["slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "slack", nodeIds: ["wdr-slack"], description: "Slack credential for urgent alerts" },
            { platform: "discord", nodeIds: ["wdr-discord"], description: "Discord credential for standard alerts" },
        ],
        fieldRequirements: [
            {
                nodeId: "wdr-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "wdr-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Alert Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "wdr-transform",
                type: "transformNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Normalize Alert",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "alertPayload",
                    expression: '{"severity":"{wdr-webhook.payload.severity}","service":"{wdr-webhook.payload.service}","message":"{wdr-webhook.payload.message}","occurredAt":"{wdr-webhook.payload.occurredAt}"}',
                },
            },
            {
                id: "wdr-condition",
                type: "conditionNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Urgent?",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{alertPayload.data.severity}",
                    routes: ["urgent", "normal"],
                    defaultRoute: "normal",
                    rulesJson: '[{"route":"urgent","operator":"contains","value":"high"}]',
                    responseName: "alertRoute",
                },
            },
            {
                id: "wdr-slack",
                type: "slackNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Urgent Slack Alert",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "alertSlack",
                    credentialId: "",
                    channel: "",
                    message: "Urgent alert\\nService: {alertPayload.data.service}\\nSeverity: {alertPayload.data.severity}\\nEvent: {alertPayload.data.message}\\nOccurred: {alertPayload.data.occurredAt}",
                },
            },
            {
                id: "wdr-discord",
                type: "discordNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Normal Discord Alert",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "alertDiscord",
                    credentialId: "",
                    message: "Alert\\nService: {alertPayload.data.service}\\nSeverity: {alertPayload.data.severity}\\nEvent: {alertPayload.data.message}\\nOccurred: {alertPayload.data.occurredAt}",
                },
            },
            {
                id: "wdr-log",
                type: "logNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Route Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Alert routed ({alertRoute.route}) for {alertPayload.data.service} with severity {alertPayload.data.severity}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "wdr-webhook", target: "wdr-transform" },
            { id: "e2", source: "wdr-transform", target: "wdr-condition" },
            { id: "e3", source: "wdr-condition", sourceHandle: "urgent", target: "wdr-slack" },
            { id: "e4", source: "wdr-condition", sourceHandle: "normal", target: "wdr-discord" },
            { id: "e5", source: "wdr-condition", sourceHandle: "urgent", target: "wdr-log" },
            { id: "e6", source: "wdr-condition", sourceHandle: "normal", target: "wdr-log" },
        ],
    },
    {
        id: "openai-webhook-summary-discord",
        name: "OpenAI Webhook Summary to Discord",
        description: "Summarize webhook payloads with OpenAI and publish to Discord.",
        category: "webhooks-apis",
        difficulty: "intermediate",
        estimatedSetupMinutes: 7,
        tags: ["webhook", "openai", "transform", "discord"],
        availableTriggerId: "webhook",
        highlights: ["Webhook summaries", "AI response compression"],
        requiredCredentials: ["openai", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["ows-openai"], description: "OpenAI credential for summarization" },
            { platform: "discord", nodeIds: ["ows-discord"], description: "Discord credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "ows-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
        ],
        nodes: [
            {
                id: "ows-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Event Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "ows-transform",
                type: "transformNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Build Prompt",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "summaryPrompt",
                    expression: '{"event":{json ows-webhook.payload},"prompt":"Summarize this event in 3 concise bullet points."}',
                },
            },
            {
                id: "ows-openai",
                type: "openaiNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Summarize Event",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "eventSummary",
                    credentialId: "",
                    model: "",
                    prompt: "{summaryPrompt.data.prompt}\nEvent: {json summaryPrompt.data.event}",
                    temperature: 0.2,
                },
            },
            {
                id: "ows-discord",
                type: "discordNode",
                position: { x: 800, y: 180 },
                data: {
                    label: "Post Summary",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "summaryDiscord",
                    credentialId: "",
                    message: "Webhook Summary:\n{eventSummary.data}",
                },
            },
            {
                id: "ows-log",
                type: "logNode",
                position: { x: 800, y: 300 },
                data: {
                    label: "Audit Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Webhook summary posted to Discord",
                },
            },
        ],
        edges: [
            { id: "e1", source: "ows-webhook", target: "ows-transform" },
            { id: "e2", source: "ows-transform", target: "ows-openai" },
            { id: "e3", source: "ows-openai", target: "ows-discord" },
            { id: "e4", source: "ows-discord", target: "ows-log" },
        ],
    },
    {
        id: "cron-openai-health-summary",
        name: "Cron OpenAI Health Summary",
        description: "Run scheduled health checks, summarize context with OpenAI, and route alerts.",
        category: "devops",
        difficulty: "intermediate",
        estimatedSetupMinutes: 8,
        tags: ["cron", "http", "openai", "condition", "slack"],
        availableTriggerId: "manual",
        highlights: ["Scheduled checks", "AI context", "Alert routing"],
        requiredCredentials: ["openai", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["coh-openai"], description: "OpenAI credential for health summaries" },
            { platform: "slack", nodeIds: ["coh-slack"], description: "Slack credential for alerts" },
        ],
        fieldRequirements: [
            {
                nodeId: "coh-http",
                field: "url",
                label: "Healthcheck URL",
                placeholder: "https://example.com/health",
                type: "text",
                required: true,
            },
            {
                nodeId: "coh-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "coh-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "coh-cron",
                type: "cronTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Every 5 Minutes",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "every_5_minutes",
                    timezone: "UTC",
                },
            },
            {
                id: "coh-http",
                type: "httpTrigger",
                position: { x: 320, y: 220 },
                data: {
                    label: "Check API",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "cohResponse",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "coh-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Prepare Health Context",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "cohContext",
                    expression: '{"httpStatusCode":"{cohResponse.httpStatusCode}","response":{json cohResponse},"prompt":"Summarize API health and give one action recommendation."}',
                },
            },
            {
                id: "coh-openai",
                type: "openaiNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Generate Health Summary",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "cohSummary",
                    credentialId: "",
                    model: "",
                    prompt: "{cohContext.data.prompt}\nStatus={cohContext.data.httpStatusCode}\nResponse: {json cohContext.data.response}",
                    temperature: 0,
                },
            },
            {
                id: "coh-condition",
                type: "conditionNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Status OK?",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{cohContext.data.httpStatusCode}",
                    routes: ["alert", "ok"],
                    defaultRoute: "ok",
                    rulesJson: '[{"route":"alert","operator":"not_equals","value":"200"}]',
                    responseName: "cohRoute",
                },
            },
            {
                id: "coh-slack",
                type: "slackNode",
                position: { x: 1280, y: 170 },
                data: {
                    label: "Alert Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "cohSlack",
                    credentialId: "",
                    channel: "",
                    message: "Health alert: {cohSummary.data}",
                },
            },
            {
                id: "coh-log",
                type: "logNode",
                position: { x: 1280, y: 280 },
                data: {
                    label: "Health Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Health workflow processed status {cohContext.data.httpStatusCode}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "coh-cron", target: "coh-http" },
            { id: "e2", source: "coh-http", target: "coh-transform" },
            { id: "e3", source: "coh-transform", target: "coh-openai" },
            { id: "e4", source: "coh-openai", target: "coh-condition" },
            { id: "e5", source: "coh-condition", sourceHandle: "alert", target: "coh-slack" },
            { id: "e6", source: "coh-condition", sourceHandle: "ok", target: "coh-log" },
            { id: "e7", source: "coh-condition", sourceHandle: "alert", target: "coh-log" },
        ],
    },
    {
        id: "github-issue-comment-assistant",
        name: "GitHub Issue Comment Assistant",
        description: "Read GitHub issues from webhook events and post AI-generated maintainer comments.",
        category: "devops",
        difficulty: "intermediate",
        estimatedSetupMinutes: 9,
        tags: ["webhook", "github", "openai", "discord"],
        availableTriggerId: "webhook",
        highlights: ["Issue lookup", "AI comment drafting", "Automated GitHub reply"],
        requiredCredentials: ["github", "openai", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            {
                platform: "github",
                nodeIds: ["gic-github", "gic-comment"],
                description: "GitHub credential for issue read/write",
            },
            { platform: "openai", nodeIds: ["gic-openai"], description: "OpenAI credential for comment drafting" },
            { platform: "discord", nodeIds: ["gic-discord"], description: "Discord credential for notifications" },
        ],
        fieldRequirements: [
            {
                nodeId: "gic-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "gic-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "product-api",
                type: "text",
                required: true,
            },
            {
                nodeId: "gic-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
        ],
        nodes: [
            {
                id: "gic-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Issue Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "gic-github",
                type: "githubNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Load Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "gicIssue",
                    credentialId: "",
                    operation: "get_issue",
                    owner: "",
                    repo: "",
                    issueNumber: "{gic-webhook.payload.issueNumber}",
                },
            },
            {
                id: "gic-openai",
                type: "openaiNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Draft Comment",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "gicCommentDraft",
                    credentialId: "",
                    model: "",
                    prompt: "Draft a concise maintainer response for this issue: {json gicIssue.data}",
                    temperature: 0.2,
                },
            },
            {
                id: "gic-comment",
                type: "githubNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Post GitHub Comment",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "gicComment",
                    credentialId: "",
                    operation: "create_comment",
                    owner: "{gicIssue.owner}",
                    repo: "{gicIssue.repo}",
                    issueNumber: "{gic-webhook.payload.issueNumber}",
                    body: "{gicCommentDraft.data}",
                },
            },
            {
                id: "gic-discord",
                type: "discordNode",
                position: { x: 1040, y: 170 },
                data: {
                    label: "Notify Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "gicDiscord",
                    credentialId: "",
                    message: "Posted AI comment to issue #{gicComment.issueNumber}",
                },
            },
            {
                id: "gic-log",
                type: "logNode",
                position: { x: 1040, y: 280 },
                data: {
                    label: "Comment Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "GitHub issue comment assistant completed",
                },
            },
        ],
        edges: [
            { id: "e1", source: "gic-webhook", target: "gic-github" },
            { id: "e2", source: "gic-github", target: "gic-openai" },
            { id: "e3", source: "gic-openai", target: "gic-comment" },
            { id: "e4", source: "gic-comment", target: "gic-discord" },
            { id: "e5", source: "gic-discord", target: "gic-log" },
        ],
    },
    {
        id: "anthropic-standup-digest-discord",
        name: "Anthropic Standup Digest Discord",
        description: "Generate a standup digest and distribute it across Discord and Slack.",
        category: "business",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["manual", "anthropic", "transform", "discord", "slack"],
        availableTriggerId: "manual",
        highlights: ["Team standups", "Dual-channel output"],
        requiredCredentials: ["anthropic", "discord", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["asd-anthropic"], description: "Anthropic credential for digest generation" },
            { platform: "discord", nodeIds: ["asd-discord"], description: "Discord credential for posting" },
            { platform: "slack", nodeIds: ["asd-slack"], description: "Slack credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "asd-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "asd-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "asd-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "asd-anthropic",
                type: "anthropicNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Generate Standup Digest",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "asdDigest",
                    credentialId: "",
                    model: "",
                    prompt: "Create a concise standup digest with priorities and blockers for today.",
                    temperature: 0.2,
                },
            },
            {
                id: "asd-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Format Digest",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "asdPayload",
                    expression: '{"message":{json asdDigest.data}}',
                },
            },
            {
                id: "asd-discord",
                type: "discordNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Post to Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "asdDiscord",
                    credentialId: "",
                    message: "Standup Digest:\n{asdPayload.data.message}",
                },
            },
            {
                id: "asd-slack",
                type: "slackNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Post to Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "asdSlack",
                    credentialId: "",
                    channel: "",
                    message: "Standup Digest:\n{asdPayload.data.message}",
                },
            },
            {
                id: "asd-log",
                type: "logNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Standup Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Standup digest distributed",
                },
            },
        ],
        edges: [
            { id: "e1", source: "asd-manual", target: "asd-anthropic" },
            { id: "e2", source: "asd-anthropic", target: "asd-transform" },
            { id: "e3", source: "asd-transform", target: "asd-discord" },
            { id: "e4", source: "asd-transform", target: "asd-slack" },
            { id: "e5", source: "asd-discord", target: "asd-log" },
            { id: "e6", source: "asd-slack", target: "asd-log" },
        ],
    },
    {
        id: "policy-review-router",
        name: "Policy Review Router",
        description: "Draft a policy with OpenAI, validate with Anthropic, then route pass/revise outcomes.",
        category: "business",
        difficulty: "intermediate",
        estimatedSetupMinutes: 8,
        tags: ["manual", "openai", "anthropic", "condition", "slack", "discord"],
        availableTriggerId: "manual",
        highlights: ["Dual-model review", "Decision routing"],
        requiredCredentials: ["openai", "anthropic", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["prr-openai"], description: "OpenAI credential for draft generation" },
            { platform: "anthropic", nodeIds: ["prr-anthropic"], description: "Anthropic credential for validation" },
            { platform: "slack", nodeIds: ["prr-slack"], description: "Slack credential for pass notifications" },
            { platform: "discord", nodeIds: ["prr-discord"], description: "Discord credential for revise notifications" },
        ],
        fieldRequirements: [
            {
                nodeId: "prr-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "prr-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "prr-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "prr-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "prr-openai",
                type: "openaiNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Draft Policy",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "prrDraft",
                    credentialId: "",
                    model: "",
                    prompt: "Draft a short data retention policy for a SaaS team.",
                    temperature: 0.2,
                },
            },
            {
                id: "prr-anthropic",
                type: "anthropicNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Validate Policy",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "prrReview",
                    credentialId: "",
                    model: "",
                    prompt: "You are a strict policy reviewer. Evaluate the policy below and reply with exactly one lowercase word: pass or revise. Do not add any extra text.\n\nPolicy:\n{prrDraft.data}",
                    temperature: 0,
                },
            },
            {
                id: "prr-transform",
                type: "transformNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Prepare Decision",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "prrDecision",
                    expression: '{"decision":"{prrReview.data}","outcome":"Policy review outcome: {prrReview.data}","draft":{json prrDraft.data}}',
                },
            },
            {
                id: "prr-condition",
                type: "conditionNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Pass or Revise",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{prrDecision.data.decision}",
                    routes: ["pass", "revise"],
                    defaultRoute: "revise",
                    rulesJson: '[{"route":"pass","operator":"contains","value":"pass"}]',
                    responseName: "prrRoute",
                },
            },
            {
                id: "prr-slack",
                type: "slackNode",
                position: { x: 1280, y: 170 },
                data: {
                    label: "Notify Team",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "prrSlack",
                    credentialId: "",
                    channel: "",
                    message: "Policy review outcome: {prrRoute.route}\n\nDraft:\n{prrDecision.data.draft}",
                },
            },
            {
                id: "prr-discord",
                type: "discordNode",
                position: { x: 1280, y: 270 },
                data: {
                    label: "Notify Revise",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "prrDiscord",
                    credentialId: "",
                    message: "Policy review outcome: {prrRoute.route}\n\nAction: revise before approval.\n\nDraft:\n{prrDecision.data.draft}",
                },
            },
            {
                id: "prr-log",
                type: "logNode",
                position: { x: 1520, y: 220 },
                data: {
                    label: "Review Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Policy review decision route: {prrRoute.route}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "prr-manual", target: "prr-openai" },
            { id: "e2", source: "prr-openai", target: "prr-anthropic" },
            { id: "e3", source: "prr-anthropic", target: "prr-transform" },
            { id: "e4", source: "prr-transform", target: "prr-condition" },
            { id: "e5", source: "prr-condition", sourceHandle: "pass", target: "prr-slack" },
            { id: "e6a", source: "prr-condition", sourceHandle: "revise", target: "prr-slack" },
            { id: "e6", source: "prr-condition", sourceHandle: "revise", target: "prr-discord" },
            { id: "e7", source: "prr-condition", sourceHandle: "pass", target: "prr-log" },
            { id: "e8", source: "prr-condition", sourceHandle: "revise", target: "prr-log" },
        ],
    },
    {
        id: "weekly-trend-brief-discord",
        name: "Weekly Trend Brief Discord",
        description: "Fetch weekly trend data, summarize with Anthropic, and post to Discord.",
        category: "marketing",
        difficulty: "intermediate",
        estimatedSetupMinutes: 7,
        tags: ["cron", "http", "anthropic", "discord", "transform"],
        availableTriggerId: "manual",
        highlights: ["Weekly trend summaries", "Discord publishing"],
        requiredCredentials: ["anthropic", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["wtb-anthropic"], description: "Anthropic credential for trend summaries" },
            { platform: "discord", nodeIds: ["wtb-discord"], description: "Discord credential for publishing" },
        ],
        fieldRequirements: [
            {
                nodeId: "wtb-http",
                field: "url",
                label: "Trend Data URL",
                placeholder: "https://api.example.com/trends/weekly",
                type: "text",
                required: true,
            },
            {
                nodeId: "wtb-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
        ],
        nodes: [
            {
                id: "wtb-cron",
                type: "cronTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Weekly Trigger",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "weekly",
                    dayOfWeek: 1,
                    hour: 9,
                    minute: 0,
                    timezone: "UTC",
                },
            },
            {
                id: "wtb-http",
                type: "httpTrigger",
                position: { x: 320, y: 220 },
                data: {
                    label: "Fetch Trends",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "wtbTrends",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "wtb-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Build Prompt",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "wtbPrompt",
                    expression: '{"trendData":{json wtbTrends},"prompt":"Create a weekly trend brief with top 5 insights."}',
                },
            },
            {
                id: "wtb-anthropic",
                type: "anthropicNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Generate Brief",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "wtbBrief",
                    credentialId: "",
                    model: "",
                    prompt: "{wtbPrompt.data.prompt}\nData: {json wtbPrompt.data.trendData}",
                    temperature: 0.2,
                },
            },
            {
                id: "wtb-discord",
                type: "discordNode",
                position: { x: 1040, y: 180 },
                data: {
                    label: "Post to Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "wtbDiscord",
                    credentialId: "",
                    message: "Weekly Trend Brief:\n{wtbBrief.data}",
                },
            },
            {
                id: "wtb-log",
                type: "logNode",
                position: { x: 1040, y: 300 },
                data: {
                    label: "Brief Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Weekly trend brief posted",
                },
            },
        ],
        edges: [
            { id: "e1", source: "wtb-cron", target: "wtb-http" },
            { id: "e2", source: "wtb-http", target: "wtb-transform" },
            { id: "e3", source: "wtb-transform", target: "wtb-anthropic" },
            { id: "e4", source: "wtb-anthropic", target: "wtb-discord" },
            { id: "e5", source: "wtb-discord", target: "wtb-log" },
        ],
    },
    {
        id: "content-repurpose-openai-discord",
        name: "Content Repurpose OpenAI Discord",
        description: "Repurpose a product update with OpenAI and publish to Discord + Slack.",
        category: "marketing",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["manual", "openai", "transform", "discord", "slack"],
        availableTriggerId: "manual",
        highlights: ["Content repurposing", "Multi-channel posting"],
        requiredCredentials: ["openai", "discord", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["crd-openai"], description: "OpenAI credential for repurposing" },
            { platform: "discord", nodeIds: ["crd-discord"], description: "Discord credential for posting" },
            { platform: "slack", nodeIds: ["crd-slack"], description: "Slack credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "crd-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "crd-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "crd-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "crd-openai",
                type: "openaiNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Repurpose Content",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "crdCopy",
                    credentialId: "",
                    model: "",
                    prompt: "Repurpose this product update into short posts for Discord and Slack.",
                    temperature: 0.3,
                },
            },
            {
                id: "crd-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Format Channels",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "crdPayload",
                    expression: '{"discord":{json crdCopy.data},"slack":{json crdCopy.data}}',
                },
            },
            {
                id: "crd-discord",
                type: "discordNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Post Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "crdDiscord",
                    credentialId: "",
                    content: "{crdPayload.data.discord}",
                    message: "{crdPayload.data.discord}",
                },
            },
            {
                id: "crd-slack",
                type: "slackNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Post Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "crdSlack",
                    credentialId: "",
                    channel: "",
                    message: "{crdPayload.data.slack}",
                },
            },
            {
                id: "crd-log",
                type: "logNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Repurpose Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Repurposed content posted to Discord and Slack",
                },
            },
        ],
        edges: [
            { id: "e1", source: "crd-manual", target: "crd-openai" },
            { id: "e2", source: "crd-openai", target: "crd-transform" },
            { id: "e3", source: "crd-transform", target: "crd-discord" },
            { id: "e4", source: "crd-transform", target: "crd-slack" },
            { id: "e5", source: "crd-discord", target: "crd-log" },
            { id: "e6", source: "crd-slack", target: "crd-log" },
        ],
    },
    {
        id: "release-risk-review-center",
        name: "Release Risk Review Center",
        description: "Analyze release risk from GitHub issue context and route high/normal outcomes.",
        category: "ai-automation",
        difficulty: "advanced",
        estimatedSetupMinutes: 11,
        tags: ["webhook", "github", "openai", "anthropic", "condition", "slack", "discord"],
        availableTriggerId: "webhook",
        highlights: ["Release risk scoring", "Dual-model checks", "Branch routing"],
        requiredCredentials: ["github", "openai", "anthropic", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "github", nodeIds: ["rrc-github"], description: "GitHub credential for issue lookup" },
            { platform: "openai", nodeIds: ["rrc-openai"], description: "OpenAI credential for risk summary" },
            { platform: "anthropic", nodeIds: ["rrc-anthropic"], description: "Anthropic credential for risk class" },
            { platform: "slack", nodeIds: ["rrc-slack"], description: "Slack credential for high-risk alerts" },
            { platform: "discord", nodeIds: ["rrc-discord"], description: "Discord credential for normal notifications" },
        ],
        fieldRequirements: [
            {
                nodeId: "rrc-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "rrc-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "release-repo",
                type: "text",
                required: true,
            },
            {
                nodeId: "rrc-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "rrc-anthropic",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "rrc-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "rrc-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 260 },
                data: {
                    label: "Release Event Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "rrc-github",
                type: "githubNode",
                position: { x: 320, y: 260 },
                data: {
                    label: "Fetch Release Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "rrcIssue",
                    credentialId: "",
                    operation: "get_issue",
                    owner: "",
                    repo: "",
                    issueNumber: "{rrc-webhook.payload.issueNumber}",
                },
            },
            {
                id: "rrc-openai",
                type: "openaiNode",
                position: { x: 560, y: 260 },
                data: {
                    label: "Summarize Risk Signals",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "rrcSummary",
                    credentialId: "",
                    model: "",
                    prompt: "Summarize release risk factors from this issue: {json rrcIssue.data}",
                    temperature: 0.1,
                },
            },
            {
                id: "rrc-anthropic",
                type: "anthropicNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Classify Risk",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "rrcRisk",
                    credentialId: "",
                    model: "",
                    prompt: "You are a strict release risk classifier. Analyze the summary below and reply with exactly one lowercase word: high or normal. Do not add extra text.\n\nSummary:\n{rrcSummary.data}",
                    temperature: 0,
                },
            },
            {
                id: "rrc-condition",
                type: "conditionNode",
                position: { x: 1040, y: 260 },
                data: {
                    label: "Route Risk",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{rrcRisk.data}",
                    routes: ["high", "normal"],
                    defaultRoute: "normal",
                    rulesJson: '[{"route":"high","operator":"contains","value":"high"}]',
                    responseName: "rrcRoute",
                },
            },
            {
                id: "rrc-slack",
                type: "slackNode",
                position: { x: 1280, y: 180 },
                data: {
                    label: "High-Risk Alert",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "rrcSlack",
                    credentialId: "",
                    channel: "",
                    message: "Release risk route: {rrcRoute.route} for issue #{rrcIssue.issueNumber}\n\nSummary:\n{rrcSummary.data}",
                },
            },
            {
                id: "rrc-discord",
                type: "discordNode",
                position: { x: 1280, y: 280 },
                data: {
                    label: "Normal Risk Update",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "rrcDiscord",
                    credentialId: "",
                    message: "Release risk route: {rrcRoute.route} for issue #{rrcIssue.issueNumber}\n\nSummary:\n{rrcSummary.data}",
                },
            },
            {
                id: "rrc-log",
                type: "logNode",
                position: { x: 1520, y: 240 },
                data: {
                    label: "Risk Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Release risk decision route: {rrcRoute.route}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "rrc-webhook", target: "rrc-github" },
            { id: "e2", source: "rrc-github", target: "rrc-openai" },
            { id: "e3", source: "rrc-openai", target: "rrc-anthropic" },
            { id: "e4", source: "rrc-anthropic", target: "rrc-condition" },
            { id: "e5", source: "rrc-condition", sourceHandle: "high", target: "rrc-slack" },
            { id: "e6", source: "rrc-condition", sourceHandle: "normal", target: "rrc-discord" },
            { id: "e7", source: "rrc-condition", sourceHandle: "high", target: "rrc-log" },
            { id: "e8", source: "rrc-condition", sourceHandle: "normal", target: "rrc-log" },
        ],
    },
];
