import type { WorkflowTemplate } from "../types";
export const DEVOPS_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "github-release-notes-notion-publisher",
        name: "GitHub Release Notes Slack Publisher",
        description: "Create release notes from GitHub issue context and publish to Slack with an audit log.",
        category: "devops",
        difficulty: "intermediate",
        estimatedSetupMinutes: 10,
        tags: ["webhook", "github", "openai", "slack", "log"],
        availableTriggerId: "webhook",
        highlights: ["Release webhook", "AI release-note generation", "Slack distribution"],
        requiredCredentials: ["github", "openai", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "github", nodeIds: ["rel-github"], description: "GitHub credential for issue lookup" },
            { platform: "openai", nodeIds: ["rel-openai"], description: "OpenAI credential for release-note drafting" },
            { platform: "slack", nodeIds: ["rel-slack"], description: "Slack credential for release distribution" },
        ],
        fieldRequirements: [
            {
                nodeId: "rel-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "rel-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "app-repo",
                type: "text",
                required: true,
            },
            {
                nodeId: "rel-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "rel-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "rel-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Release Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "rel-github",
                type: "githubNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Fetch Release Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "releaseIssue",
                    credentialId: "",
                    operation: "get_issue",
                    owner: "",
                    repo: "",
                    issueNumber: "{rel-webhook.payload.issueNumber}",
                },
            },
            {
                id: "rel-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Build Release Context",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "releaseContext",
                    expression: '{"version":"{rel-webhook.payload.version}","issue":"{json releaseIssue}","summary":"Build release notes for version {rel-webhook.payload.version}"}',
                },
            },
            {
                id: "rel-openai",
                type: "openaiNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Draft Release Notes",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "releaseNotes",
                    credentialId: "",
                    model: "",
                    systemPrompt: "You are a release manager. Draft concise release notes.",
                    prompt: "Context: {json releaseContext}. Produce markdown release notes.",
                    temperature: 0.2,
                },
            },
            {
                id: "rel-slack",
                type: "slackNode",
                position: { x: 1040, y: 220 },
                data: {
                    label: "Post Slack Update",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "releaseSlack",
                    credentialId: "",
                    channel: "",
                    message: "Release {rel-webhook.payload.version} notes ready:\n{releaseNotes.data}",
                },
            },
            {
                id: "rel-log",
                type: "logNode",
                position: { x: 1280, y: 220 },
                data: {
                    label: "Release Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Release notes generated for {rel-webhook.payload.version}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "rel-webhook", target: "rel-github" },
            { id: "e2", source: "rel-github", target: "rel-transform" },
            { id: "e3", source: "rel-transform", target: "rel-openai" },
            { id: "e4", source: "rel-openai", target: "rel-slack" },
            { id: "e5", source: "rel-slack", target: "rel-log" },
        ],
    },
    {
        id: "incident-response-command-center",
        name: "Incident Response Command Center",
        description: "Centralized incident intake with AI triage and multi-channel routing.",
        category: "devops",
        difficulty: "advanced",
        estimatedSetupMinutes: 14,
        tags: ["webhook", "anthropic", "github", "condition", "slack", "discord"],
        availableTriggerId: "webhook",
        highlights: ["Incident intake", "AI triage", "Conditional routing"],
        requiredCredentials: ["anthropic", "github", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["ir-ai"], description: "Anthropic credential for severity scoring" },
            { platform: "github", nodeIds: ["ir-gh"], description: "GitHub credential for issue creation" },
            { platform: "slack", nodeIds: ["ir-slack"], description: "Slack credential for paging" },
            { platform: "discord", nodeIds: ["ir-discord"], description: "Discord credential for ops updates" },
        ],
        fieldRequirements: [
            {
                nodeId: "ir-ai",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "ir-gh",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "ir-gh",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "ops-incidents",
                type: "text",
                required: true,
            },
            {
                nodeId: "ir-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "ir-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 280 },
                data: {
                    label: "Incident Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "ir-transform",
                type: "transformNode",
                position: { x: 320, y: 280 },
                data: {
                    label: "Normalize Incident",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "incidentPayload",
                    expression: '{"service":"{ir-webhook.payload.service}","severity":"{ir-webhook.payload.severity}","summary":"{ir-webhook.payload.message}","occurredAt":"{ir-webhook.payload.occurredAt}"}',
                },
            },
            {
                id: "ir-ai",
                type: "anthropicNode",
                position: { x: 560, y: 280 },
                data: {
                    label: "Assess Urgency",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "incidentTriage",
                    credentialId: "",
                    model: "",
                    systemPrompt: "Classify severity as critical or normal.",
                    prompt: "Incident data: {json incidentPayload}. Return critical or normal only.",
                    temperature: 0,
                },
            },
            {
                id: "ir-gh",
                type: "githubNode",
                position: { x: 800, y: 280 },
                data: {
                    label: "Create Incident Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "incidentIssue",
                    credentialId: "",
                    operation: "create_issue",
                    owner: "",
                    repo: "",
                    title: "[INCIDENT] {incidentPayload.data.service}",
                    body: "{incidentPayload.data.summary}",
                    labelsTemplate: '["incident","auto"]',
                },
            },
            {
                id: "ir-condition",
                type: "conditionNode",
                position: { x: 1040, y: 280 },
                data: {
                    label: "Route by Severity",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{incidentTriage.data}",
                    routes: ["critical", "normal"],
                    defaultRoute: "normal",
                    rulesJson: '[{"route":"critical","operator":"contains","value":"critical"}]',
                    responseName: "incidentRoute",
                },
            },
            {
                id: "ir-slack",
                type: "slackNode",
                position: { x: 1280, y: 180 },
                data: {
                    label: "Critical Slack Alert",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "incidentSlack",
                    credentialId: "",
                    channel: "",
                    message: "Critical incident opened: #{incidentIssue.issueNumber}",
                },
            },
            {
                id: "ir-discord",
                type: "discordNode",
                position: { x: 1280, y: 280 },
                data: {
                    label: "Ops Discord Alert",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "incidentDiscord",
                    credentialId: "",
                    message: "Critical incident: #{incidentIssue.issueNumber}",
                },
            },
            {
                id: "ir-log",
                type: "logNode",
                position: { x: 1280, y: 380 },
                data: {
                    label: "Normal Incident Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Incident routed to normal handling for {incidentPayload.data.service}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "ir-webhook", target: "ir-transform" },
            { id: "e2", source: "ir-transform", target: "ir-ai" },
            { id: "e3", source: "ir-ai", target: "ir-gh" },
            { id: "e4", source: "ir-gh", target: "ir-condition" },
            { id: "e5", source: "ir-condition", sourceHandle: "critical", target: "ir-slack" },
            { id: "e6", source: "ir-condition", sourceHandle: "critical", target: "ir-discord" },
            { id: "e7", source: "ir-condition", sourceHandle: "normal", target: "ir-log" },
        ],
    },
    {
        id: "cron-api-health-watch-lite",
        name: "Cron API Health Watch Lite",
        description: "Run scheduled health checks and route alerts based on response health.",
        category: "devops",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["cron", "http", "transform", "condition", "slack"],
        availableTriggerId: "manual",
        highlights: ["Recurring health checks", "Status routing", "Slack alerting"],
        requiredCredentials: ["slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "slack", nodeIds: ["health-slack"], description: "Slack credential for unhealthy alerts" },
        ],
        fieldRequirements: [
            {
                nodeId: "health-http",
                field: "url",
                label: "Healthcheck URL",
                placeholder: "https://example.com/health",
                type: "text",
                required: true,
            },
            {
                nodeId: "health-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "health-cron",
                type: "cronTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Every 5 Minutes",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "every_5_minutes",
                    timezone: "UTC",
                },
            },
            {
                id: "health-http",
                type: "httpTrigger",
                position: { x: 320, y: 220 },
                data: {
                    label: "Health Request",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "healthResponse",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "health-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Map Health Status",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "healthState",
                    expression: '{"httpStatusCode":"{healthResponse.httpStatusCode}","state":"{healthResponse.httpStatusCode}","body":{json healthResponse}}',
                },
            },
            {
                id: "health-condition",
                type: "conditionNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Healthy?",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{healthState.data.httpStatusCode}",
                    routes: ["unhealthy", "healthy"],
                    defaultRoute: "healthy",
                    rulesJson: '[{"route":"unhealthy","operator":"not_equals","value":"200"}]',
                    responseName: "healthRoute",
                },
            },
            {
                id: "health-slack",
                type: "slackNode",
                position: { x: 1040, y: 160 },
                data: {
                    label: "Send Health Status",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "healthSlack",
                    credentialId: "",
                    channel: "",
                    message: "API check result. Status={healthState.data.httpStatusCode}",
                },
            },
            {
                id: "health-log",
                type: "logNode",
                position: { x: 1040, y: 280 },
                data: {
                    label: "Healthy Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "API health check processed at {health-cron.triggeredAt}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "health-cron", target: "health-http" },
            { id: "e2", source: "health-http", target: "health-transform" },
            { id: "e3", source: "health-transform", target: "health-condition" },
            { id: "e4", source: "health-condition", sourceHandle: "unhealthy", target: "health-slack" },
            { id: "e5", source: "health-condition", sourceHandle: "healthy", target: "health-slack" },
            { id: "e6", source: "health-slack", target: "health-log" },
        ],
    },
];
