import type { WorkflowTemplate } from "../types";
export const MARKETING_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "gemini-social-post-sprint-lite",
        name: "AI Social Post Sprint Lite",
        description: "Generate social post ideas with Anthropic and share to Slack + Discord.",
        category: "marketing",
        difficulty: "beginner",
        estimatedSetupMinutes: 4,
        tags: ["manual", "anthropic", "transform", "slack", "discord"],
        availableTriggerId: "manual",
        highlights: ["Fast social ideation", "Slack + Discord handoff"],
        requiredCredentials: ["anthropic", "slack", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["social-gemini"], description: "Anthropic credential for idea generation" },
            { platform: "slack", nodeIds: ["social-slack"], description: "Slack credential for team sharing" },
            { platform: "discord", nodeIds: ["social-discord"], description: "Discord credential for community sharing" },
        ],
        fieldRequirements: [
            {
                nodeId: "social-gemini",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "social-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "social-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "social-gemini",
                type: "anthropicNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Generate Ideas",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "socialIdeas",
                    credentialId: "",
                    model: "",
                    prompt: "Create 5 short social content ideas for a developer automation product.",
                    temperature: 0.7,
                },
            },
            {
                id: "social-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Format Output",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "socialOutput",
                    expression: '{"message":{json socialIdeas.data}}',
                },
            },
            {
                id: "social-slack",
                type: "slackNode",
                position: { x: 800, y: 140 },
                data: {
                    label: "Share in Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "socialSlack",
                    credentialId: "",
                    channel: "",
                    message: "New content ideas:\n{socialOutput.data.message}",
                },
            },
            {
                id: "social-discord",
                type: "discordNode",
                position: { x: 800, y: 240 },
                data: {
                    label: "Share in Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "socialDiscord",
                    credentialId: "",
                    message: "New content ideas:\n{socialOutput.data.message}",
                },
            },
            {
                id: "social-log",
                type: "logNode",
                position: { x: 800, y: 340 },
                data: {
                    label: "Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Social post ideation workflow completed",
                },
            },
        ],
        edges: [
            { id: "e1", source: "social-manual", target: "social-gemini" },
            { id: "e2", source: "social-gemini", target: "social-transform" },
            { id: "e3", source: "social-transform", target: "social-slack" },
            { id: "e4", source: "social-transform", target: "social-discord" },
            { id: "e5", source: "social-slack", target: "social-log" },
        ],
    },
    {
        id: "weekly-campaign-briefing-discord",
        name: "Weekly Campaign Briefing Discord",
        description: "Fetch campaign metrics weekly, summarize with Anthropic, and post to Discord.",
        category: "marketing",
        difficulty: "intermediate",
        estimatedSetupMinutes: 8,
        tags: ["cron", "http", "anthropic", "discord", "transform"],
        availableTriggerId: "manual",
        highlights: ["Weekly digest", "AI summary", "Discord distribution"],
        requiredCredentials: ["anthropic", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "anthropic", nodeIds: ["campaign-ai"], description: "Anthropic credential for summary drafting" },
            { platform: "discord", nodeIds: ["campaign-discord"], description: "Discord credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "campaign-http",
                field: "url",
                label: "Campaign Metrics URL",
                placeholder: "https://api.example.com/marketing/weekly",
                type: "text",
                required: true,
            },
            {
                nodeId: "campaign-ai",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
        ],
        nodes: [
            {
                id: "campaign-cron",
                type: "cronTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Weekly Schedule",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "weekly",
                    dayOfWeek: 1,
                    hour: 9,
                    minute: 0,
                    timezone: "UTC",
                },
            },
            {
                id: "campaign-http",
                type: "httpTrigger",
                position: { x: 320, y: 220 },
                data: {
                    label: "Fetch Campaign Data",
                    nodeType: "httpTrigger",
                    isConfigured: false,
                    responseName: "campaignMetrics",
                    method: "GET",
                    url: "",
                    headers: [],
                },
            },
            {
                id: "campaign-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Prepare Brief Context",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "campaignContext",
                    expression: '{"summary":"Create a weekly campaign brief from this data.","metrics":{json campaignMetrics}}',
                },
            },
            {
                id: "campaign-ai",
                type: "anthropicNode",
                position: { x: 800, y: 220 },
                data: {
                    label: "Generate Brief",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "campaignBrief",
                    credentialId: "",
                    model: "",
                    prompt: "{campaignContext.data.summary}\n{json campaignContext.data.metrics}",
                    temperature: 0.3,
                },
            },
            {
                id: "campaign-discord",
                type: "discordNode",
                position: { x: 1040, y: 180 },
                data: {
                    label: "Post to Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "campaignDiscord",
                    credentialId: "",
                    message: "Weekly Campaign Brief:\n{campaignBrief.data}",
                },
            },
            {
                id: "campaign-log",
                type: "logNode",
                position: { x: 1040, y: 300 },
                data: {
                    label: "Log Dispatch",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Weekly campaign briefing posted to Discord",
                },
            },
        ],
        edges: [
            { id: "e1", source: "campaign-cron", target: "campaign-http" },
            { id: "e2", source: "campaign-http", target: "campaign-transform" },
            { id: "e3", source: "campaign-transform", target: "campaign-ai" },
            { id: "e4", source: "campaign-ai", target: "campaign-discord" },
            { id: "e5", source: "campaign-discord", target: "campaign-log" },
        ],
    },
    {
        id: "discord-announcement-generator-lite",
        name: "Discord Announcement Generator Lite",
        description: "Generate announcement copy with OpenAI and publish directly to Discord.",
        category: "marketing",
        difficulty: "beginner",
        estimatedSetupMinutes: 4,
        tags: ["manual", "openai", "discord", "transform"],
        availableTriggerId: "manual",
        highlights: ["Announcement drafting", "Discord posting"],
        requiredCredentials: ["openai", "discord"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["announce-gemini"], description: "OpenAI credential for copy generation" },
            { platform: "discord", nodeIds: ["announce-discord"], description: "Discord credential for posting" },
        ],
        fieldRequirements: [
            {
                nodeId: "announce-gemini",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
        ],
        nodes: [
            {
                id: "announce-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "announce-gemini",
                type: "openaiNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Draft Announcement",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "announcementDraft",
                    credentialId: "",
                    model: "",
                    prompt: "Write exactly one Discord-ready product announcement for new workflow features. Keep it under 1200 characters, plain text only, no options, no section headers.",
                    temperature: 0.4,
                },
            },
            {
                id: "announce-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Format Message",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "announcementPayload",
                    expression: '{"message":{json announcementDraft.data}}',
                },
            },
            {
                id: "announce-discord",
                type: "discordNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Post to Discord",
                    nodeType: "discordNode",
                    isConfigured: false,
                    responseName: "announceDiscord",
                    credentialId: "",
                    message: "📣 Product Update\n{announcementPayload.data.message}",
                },
            },
            {
                id: "announce-log",
                type: "logNode",
                position: { x: 800, y: 280 },
                data: {
                    label: "Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Announcement posted to Discord",
                },
            },
        ],
        edges: [
            { id: "e1", source: "announce-manual", target: "announce-gemini" },
            { id: "e2", source: "announce-gemini", target: "announce-transform" },
            { id: "e3", source: "announce-transform", target: "announce-discord" },
            { id: "e4", source: "announce-discord", target: "announce-log" },
        ],
    },
];
