import type { WorkflowTemplate } from "../types";
export const WEBHOOKS_APIS_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "webhook-github-issue-alert-lite",
        name: "Webhook GitHub Issue Alert Lite",
        description: "Convert inbound webhook incidents into GitHub issues and post updates to Slack.",
        category: "webhooks-apis",
        difficulty: "beginner",
        estimatedSetupMinutes: 6,
        tags: ["webhook", "github", "slack", "transform"],
        availableTriggerId: "webhook",
        highlights: ["Incident intake", "GitHub issue creation", "Slack alert"],
        requiredCredentials: ["github", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            {
                platform: "github",
                nodeIds: ["wh-github"],
                description: "GitHub credential for issue creation",
            },
            {
                platform: "slack",
                nodeIds: ["wh-slack"],
                description: "Slack credential for alerting",
            },
        ],
        fieldRequirements: [
            {
                nodeId: "wh-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "wh-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "incident-tracker",
                type: "text",
                required: true,
            },
            {
                nodeId: "wh-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "wh-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Incident Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "wh-transform",
                type: "transformNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Normalize Payload",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "issuePayload",
                    expression: '{"title":"[{wh-webhook.payload.severity}] {wh-webhook.payload.service}","body":"Summary: {wh-webhook.payload.message}\\nOccurredAt: {wh-webhook.payload.occurredAt}"}',
                },
            },
            {
                id: "wh-github",
                type: "githubNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Create Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "createdIssue",
                    credentialId: "",
                    operation: "create_issue",
                    owner: "",
                    repo: "",
                    title: "{issuePayload.data.title}",
                    body: "{issuePayload.data.body}",
                    labelsTemplate: '["incident","auto"]',
                },
            },
            {
                id: "wh-slack",
                type: "slackNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Notify Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "slackAlert",
                    credentialId: "",
                    channel: "",
                    message: "Created issue #{createdIssue.issueNumber}: {issuePayload.data.title}",
                },
            },
            {
                id: "wh-log",
                type: "logNode",
                position: { x: 800, y: 280 },
                data: {
                    label: "Audit Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Issue creation workflow completed for {issuePayload.data.title}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "wh-webhook", target: "wh-transform" },
            { id: "e2", source: "wh-transform", target: "wh-github" },
            { id: "e3", source: "wh-github", target: "wh-slack" },
            { id: "e4", source: "wh-github", target: "wh-log" },
        ],
    },
    {
        id: "github-bug-triage-router",
        name: "GitHub Bug Triage Router",
        description: "Use webhook events + Anthropic triage to route urgent bug notifications.",
        category: "webhooks-apis",
        difficulty: "intermediate",
        estimatedSetupMinutes: 9,
        tags: ["webhook", "github", "anthropic", "condition", "slack"],
        availableTriggerId: "webhook",
        highlights: ["GitHub issue fetch", "AI triage", "Priority routing"],
        requiredCredentials: ["github", "anthropic", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            {
                platform: "github",
                nodeIds: ["bug-github"],
                description: "GitHub credential for reading issues",
            },
            {
                platform: "anthropic",
                nodeIds: ["bug-ai"],
                description: "Anthropic credential for severity classification",
            },
            {
                platform: "slack",
                nodeIds: ["bug-slack"],
                description: "Slack credential for urgent alerts",
            },
        ],
        fieldRequirements: [
            {
                nodeId: "bug-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "bug-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "product-api",
                type: "text",
                required: true,
            },
            {
                nodeId: "bug-ai",
                field: "model",
                label: "Anthropic Model",
                placeholder: "claude-sonnet-4-5",
                type: "select",
                required: true,
                options: [
                    { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5 (Recommended)" },
                    { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
                    { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
                ],
                defaultValue: "claude-sonnet-4-5",
            },
            {
                nodeId: "bug-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "bug-webhook",
                type: "webhookTrigger",
                position: { x: 80, y: 240 },
                data: {
                    label: "GitHub Event Webhook",
                    nodeType: "webhookTrigger",
                    isConfigured: true,
                    secret: "change-this-secret",
                },
            },
            {
                id: "bug-github",
                type: "githubNode",
                position: { x: 320, y: 240 },
                data: {
                    label: "Get Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "bugIssue",
                    credentialId: "",
                    operation: "get_issue",
                    owner: "",
                    repo: "",
                    issueNumber: "{bug-webhook.payload.issueNumber}",
                },
            },
            {
                id: "bug-ai",
                type: "anthropicNode",
                position: { x: 560, y: 240 },
                data: {
                    label: "Classify Severity",
                    nodeType: "anthropicNode",
                    isConfigured: false,
                    responseName: "bugClass",
                    credentialId: "",
                    model: "",
                    systemPrompt: "You are a strict severity classifier.",
                    prompt: "Classify production bug urgency from this issue payload. Reply with exactly one lowercase word: high or normal. Do not add extra text.\n\nIssue payload:\n{json bugIssue}",
                    temperature: 0,
                },
            },
            {
                id: "bug-condition",
                type: "conditionNode",
                position: { x: 800, y: 240 },
                data: {
                    label: "Route Priority",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{bugClass.data}",
                    routes: ["urgent", "normal"],
                    defaultRoute: "normal",
                    rulesJson: '[{"route":"urgent","operator":"contains","value":"high"}]',
                    responseName: "bugRoute",
                },
            },
            {
                id: "bug-slack",
                type: "slackNode",
                position: { x: 1040, y: 180 },
                data: {
                    label: "Urgent Alert",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "bugSlack",
                    credentialId: "",
                    channel: "",
                    message: "Bug triage route: {bugRoute.route} for issue {bug-webhook.payload.issueNumber}",
                },
            },
            {
                id: "bug-log",
                type: "logNode",
                position: { x: 1040, y: 300 },
                data: {
                    label: "Triage Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Bug triage completed for issue {bug-webhook.payload.issueNumber} (route={bugRoute.route})",
                },
            },
        ],
        edges: [
            { id: "e1", source: "bug-webhook", target: "bug-github" },
            { id: "e2", source: "bug-github", target: "bug-ai" },
            { id: "e3", source: "bug-ai", target: "bug-condition" },
            { id: "e4", source: "bug-condition", sourceHandle: "urgent", target: "bug-slack" },
            { id: "e5", source: "bug-condition", sourceHandle: "normal", target: "bug-log" },
            { id: "e6", source: "bug-condition", sourceHandle: "urgent", target: "bug-log" },
        ],
    },
];
